// scripts/test-hmac-tokens.ts — wire-compatibility and behaviour tests for the
// five HMAC token kinds that now share lib/hmacToken.ts.
//
// WHY THIS SCRIPT EXISTS
// Tokens minted before the consolidation are in the wild: opt-out links live in
// email footers for a year, outreach reply tokens for 90 days, availability
// picker links for 7 days, and an OAuth state can be sitting in a browser
// mid-consent. The shared module therefore had to keep every wire format
// byte-identical. The OLD_* constants below are the proof: each was produced by
// the PRE-consolidation code (commit e71a05d) via this script's own
// `--emit-fixtures` mode, then pasted here. They must keep verifying forever.
//
// HOW THE FIXTURES WERE PRODUCED
//   AVAILABILITY_TOKEN_SECRET=<FIXTURE_SECRET below> npx tsx scripts/test-hmac-tokens.ts --emit-fixtures
// run against the old lib/optOutToken.ts, lib/outreachToken.ts,
// lib/availabilityToken.ts and lib/onboardingOauthState.ts, with Date.now()
// stubbed (see emitFixtures) so the "future" tokens carry a year-2100 expiry
// and the "past" ones a year-2020 expiry. Re-running the mode today regenerates
// them with the NEW code; the constants stay as the old code left them.
//
// FIXTURE_SECRET is not a secret: it is a throwaway 32-character string that
// exists only so the fixtures are reproducible. Nothing signed with it is
// accepted anywhere.
//
// Run: npx tsx scripts/test-hmac-tokens.ts

process.env.AVAILABILITY_TOKEN_SECRET = 'expertmatch-fixture-secret-0123456789';

import { sign, verify, constantTimeEqual } from '../lib/hmacToken';
import { generateOptOutToken, verifyOptOutToken } from '../lib/optOutToken';
import { generateOutreachToken, verifyOutreachToken, hashOutreachToken } from '../lib/outreachToken';
import {
  generateAvailabilityToken,
  generateClientAvailabilityToken,
  verifyAvailabilityToken,
  hashToken,
} from '../lib/availabilityToken';
import { buildOnboardingOAuthState, verifyOnboardingOAuthState } from '../lib/onboardingOauthState';
import { check, eq, summary } from './testHarness';

function section(title: string): void {
  console.log(`\n── ${title} ──`);
}

// ─── Fixtures produced by the OLD (pre-hmacToken) implementations ─────────────
// Generated by `--emit-fixtures` at commit e71a05d. Do not regenerate.

const OLD_OPTOUT_FUTURE      = 'b3B0b3V0OmJXVkFaWGhoYlhCc1pTNWpiMjA6NDEzMzk4MDgwMDAwMDo3NmY3MzEyOWEzNmEyMjBkNDcyNmZjODYxN2NhMWNiYg.BYozvtqCKI7BsOwne0szI-z1RW7f5sgXOb1guj1yVdk';
const OLD_OPTOUT_PAST        = 'b3B0b3V0OmJXVkFaWGhoYlhCc1pTNWpiMjA6MTYwOTM3MjgwMDAwMDoxNzQ1YmNmM2NjOGZkZGQ5NzAzNDZjMTIxZWIzMDUzMw.oU7FU3Upkf3sSAEzDGIBdI2AdH5a4tYu9jfM32Pu5wE';
const OLD_OUTREACH_FUTURE    = 'cHJval9maXh0dXJlOmV4cF9maXh0dXJlOjQxMTAyMjA4MDAwMDA6ZGJlOGFmMGVhYzc0NzFhZjNiZGU3N2MyNTVjMWZhNjU.nIQ5dfXkHSQY0MRyX7AbmC1wPPlqqH-dOW7Fl2yvtaY';
const OLD_OUTREACH_PAST      = 'cHJval9maXh0dXJlOmV4cF9maXh0dXJlOjE1ODU2MTI4MDAwMDA6OWNjOGQ2MGI1NzBhMzM0MDJjNjE4MjQ2ZDQ4YWE2NWY.zwxUQIjE4khZaRVSSrk4uFFFC-tpcJDcn9iHflIUvwc';
const OLD_AVAIL_EXPERT       = 'cHJval9maXh0dXJlOmV4cF9maXh0dXJlOjQxMDMwNDk2MDAwMDA6YWJhMDRiMTE2OTBlZTlmYzA0MzY0MTgxMjgwYWUxMjc.1p003lNQ5enlyyakhVzi7upi32_6zPbR2t0_A-0HrNI';
const OLD_AVAIL_EXPERT_PAST  = 'cHJval9maXh0dXJlOmV4cF9maXh0dXJlOjE1Nzg0NDE2MDAwMDA6ODE3NmJlNDM4YTQ0NjcwYjk1ZmNjYmMxMDdlODZhYzI.ARE1--APVZTsIrvtcbt1q0JORRe6DEwPgXHB1mx1BAU';
const OLD_AVAIL_CLIENT       = 'Y2xpZW50OnByb2pfZml4dHVyZTo0MTAzMDQ5NjAwMDAwOjAxYTY4OTFhZmFkYjBkMjI2ZDVmODQ3OTc3MjJmNDA1._apcXI81tMNEG2SDqlUvpyGqOboxRudt7HT9QuDi988';
const OLD_ONBOARDING_STATE   = 'ZXhwZXJ0JTQwZXhhbXBsZS5jb206Zml4dHVyZS1ub25jZS0wMTpBbWVyaWNhJTJGTmV3X1lvcmsuMjExNGNlMDU4ZDRmZTJjY2I4MzQyMmRhZTk2NjJhM2Y0NGQ0NzMwNzg4MzhjNGIxZGY0NjhjNjcxODNhYWE3YQ';
const OLD_EXPERT_OAUTH_STATE = 'cHJval9maXh0dXJlOmV4cF9maXh0dXJlOmZpeHR1cmUtbm9uY2UtMDI6dG9rX2ZpeHR1cmUuZjBlYmQ4MmZhODUxMmRhODQ0OGQ2MDNiNzQwZDYxOTgyNmE5N2JlODc0OTBjNDUyYTI5ZDc0ODFlNDdmODlmOA';

const FIXTURE_EMAIL     = 'me@example.com';
const FIXTURE_PROJECT   = 'proj_fixture';
const FIXTURE_EXPERT    = 'exp_fixture';
const FIXTURE_NONCE_ON  = 'fixture-nonce-01';
const FIXTURE_NONCE_EX  = 'fixture-nonce-02';
const FIXTURE_TZ        = 'America/New_York';
const FIXTURE_PICKER    = 'tok_fixture';

// ─── The OLD inline expert-OAuth state, copied verbatim ───────────────────────
// app/api/availability/[token]/google-auth/route.ts buildState() and
// app/api/availability/oauth/google/callback/route.ts verifyState() as they read
// at commit e71a05d. Kept here so the migrated routes can be proved to produce
// and accept exactly the same bytes.

import { createHmac, timingSafeEqual } from 'crypto';

function oldBuildExpertState(projectId: string, expertId: string, nonce: string, token: string): string {
  const secret   = process.env.AVAILABILITY_TOKEN_SECRET as string;
  const payload  = `${projectId}:${expertId}:${nonce}:${token}`;
  const sig      = createHmac('sha256', secret).update(payload).digest('hex');
  return Buffer.from(`${payload}.${sig}`).toString('base64url');
}

function oldVerifyExpertState(stateB64: string, storedNonce: string):
  { ok: false } | { ok: true; projectId: string; expertId: string; token: string } {
  const secret = process.env.AVAILABILITY_TOKEN_SECRET as string;
  let decoded: string;
  try { decoded = Buffer.from(stateB64, 'base64url').toString('utf8'); } catch { return { ok: false }; }
  const lastDot = decoded.lastIndexOf('.');
  if (lastDot < 0) return { ok: false };
  const payload   = decoded.slice(0, lastDot);
  const sigActual = decoded.slice(lastDot + 1);
  const sigExpected = createHmac('sha256', secret).update(payload).digest('hex');
  const expBuf = Buffer.from(sigExpected, 'utf8');
  const actBuf = Buffer.from(sigActual,   'utf8');
  if (expBuf.length !== actBuf.length) return { ok: false };
  if (!timingSafeEqual(expBuf, actBuf))  return { ok: false };
  const parts = payload.split(':');
  if (parts.length !== 3 && parts.length !== 4) return { ok: false };
  const [projectId, expertId, nonce] = parts;
  const token = parts[3] ?? '';
  const nonceExpBuf = Buffer.from(storedNonce, 'utf8');
  const nonceActBuf = Buffer.from(nonce,       'utf8');
  if (nonceExpBuf.length !== nonceActBuf.length) return { ok: false };
  if (!timingSafeEqual(nonceExpBuf, nonceActBuf)) return { ok: false };
  return { ok: true, projectId, expertId, token };
}

// ─── Fixture emission (run once, against the OLD code) ────────────────────────

const FAR_FUTURE = Date.UTC(2100, 0, 1);   // + each module's own expiry window
const LONG_PAST  = Date.UTC(2020, 0, 1);

function atClock<T>(nowMs: number, fn: () => T): T {
  const realNow = Date.now;
  Date.now = () => nowMs;
  try { return fn(); } finally { Date.now = realNow; }
}

function emitFixtures(): void {
  console.log('OLD_OPTOUT_FUTURE     =', atClock(FAR_FUTURE, () => generateOptOutToken(FIXTURE_EMAIL)));
  console.log('OLD_OPTOUT_PAST       =', atClock(LONG_PAST,  () => generateOptOutToken(FIXTURE_EMAIL)));
  console.log('OLD_OUTREACH_FUTURE   =', atClock(FAR_FUTURE, () => generateOutreachToken(FIXTURE_PROJECT, FIXTURE_EXPERT).token));
  console.log('OLD_OUTREACH_PAST     =', atClock(LONG_PAST,  () => generateOutreachToken(FIXTURE_PROJECT, FIXTURE_EXPERT).token));
  console.log('OLD_AVAIL_EXPERT      =', atClock(FAR_FUTURE, () => generateAvailabilityToken(FIXTURE_PROJECT, FIXTURE_EXPERT).token));
  console.log('OLD_AVAIL_EXPERT_PAST =', atClock(LONG_PAST,  () => generateAvailabilityToken(FIXTURE_PROJECT, FIXTURE_EXPERT).token));
  console.log('OLD_AVAIL_CLIENT      =', atClock(FAR_FUTURE, () => generateClientAvailabilityToken(FIXTURE_PROJECT).token));
  console.log('OLD_ONBOARDING_STATE  =', buildOnboardingOAuthState({ email: 'expert@example.com', nonce: FIXTURE_NONCE_ON, timezone: FIXTURE_TZ }));
  console.log('OLD_EXPERT_OAUTH_STATE=', oldBuildExpertState(FIXTURE_PROJECT, FIXTURE_EXPERT, FIXTURE_NONCE_EX, FIXTURE_PICKER));
}

if (process.argv.includes('--emit-fixtures')) {
  emitFixtures();
  process.exit(0);
}

// ─── 1. Tokens already in the wild still verify ───────────────────────────────

section('old fixtures still verify (wire compatibility)');

const optOutOld = verifyOptOutToken(OLD_OPTOUT_FUTURE);
check('old opt-out token verifies', optOutOld.ok, JSON.stringify(optOutOld));
eq('old opt-out email round-trips', optOutOld.ok ? optOutOld.email : null, FIXTURE_EMAIL);
eq('old expired opt-out reports expired', verifyOptOutToken(OLD_OPTOUT_PAST).ok === false
  ? (verifyOptOutToken(OLD_OPTOUT_PAST) as { reason: string }).reason : 'ok', 'expired');

const outreachOld = verifyOutreachToken(OLD_OUTREACH_FUTURE);
check('old outreach token verifies', outreachOld.ok, JSON.stringify(outreachOld));
eq('old outreach projectId', outreachOld.ok ? outreachOld.data.projectId : null, FIXTURE_PROJECT);
eq('old outreach expertId',  outreachOld.ok ? outreachOld.data.expertId  : null, FIXTURE_EXPERT);
const outreachOldPast = verifyOutreachToken(OLD_OUTREACH_PAST);
eq('old expired outreach reports expired', outreachOldPast.ok ? 'ok' : outreachOldPast.reason, 'expired');

const availOld = verifyAvailabilityToken(OLD_AVAIL_EXPERT);
check('old expert availability token verifies', availOld.ok, JSON.stringify(availOld));
eq('old availability type', availOld.ok ? availOld.data.type : null, 'expert');
eq('old availability projectId', availOld.ok ? availOld.data.projectId : null, FIXTURE_PROJECT);
eq('old availability expertId',  availOld.ok ? availOld.data.expertId  : null, FIXTURE_EXPERT);
const availOldPast = verifyAvailabilityToken(OLD_AVAIL_EXPERT_PAST);
eq('old expired availability reports expired', availOldPast.ok ? 'ok' : availOldPast.reason, 'expired');

const clientOld = verifyAvailabilityToken(OLD_AVAIL_CLIENT);
check('old client availability token verifies', clientOld.ok, JSON.stringify(clientOld));
eq('old client token type', clientOld.ok ? clientOld.data.type : null, 'client');
eq('old client token expertId is null', clientOld.ok ? clientOld.data.expertId : 'x', null);

const onboardingOld = verifyOnboardingOAuthState(OLD_ONBOARDING_STATE, FIXTURE_NONCE_ON);
check('old onboarding OAuth state verifies', onboardingOld !== null, JSON.stringify(onboardingOld));
eq('old onboarding state email',    onboardingOld?.email    ?? null, 'expert@example.com');
eq('old onboarding state timezone', onboardingOld?.timezone ?? null, FIXTURE_TZ);

// The expert OAuth state lives inline in two route files. Proving the shared
// module produces and accepts the identical bytes proves those routes still
// speak the old wire format.
const expertStatePayload = `${FIXTURE_PROJECT}:${FIXTURE_EXPERT}:${FIXTURE_NONCE_EX}:${FIXTURE_PICKER}`;
eq('shared sign() reproduces the old expert OAuth state byte for byte',
  sign(expertStatePayload, 'expert-oauth'), OLD_EXPERT_OAUTH_STATE);
const expertStateOld = verify(OLD_EXPERT_OAUTH_STATE, 'expert-oauth');
check('shared verify() accepts the old expert OAuth state', expertStateOld.ok, JSON.stringify(expertStateOld));
eq('old expert OAuth payload round-trips', expertStateOld.ok ? expertStateOld.payload : null, expertStatePayload);
check('the old inline verifier accepts what sign() now produces',
  oldVerifyExpertState(sign(expertStatePayload, 'expert-oauth'), FIXTURE_NONCE_EX).ok);

// ─── 2. New tokens round-trip ────────────────────────────────────────────────

section('new tokens round-trip');

const freshOptOut = generateOptOutToken('  Mixed.Case@Example.COM  ');
const freshOptOutV = verifyOptOutToken(freshOptOut);
check('fresh opt-out verifies', freshOptOutV.ok);
eq('fresh opt-out lower-cases and trims', freshOptOutV.ok ? freshOptOutV.email : null, 'mixed.case@example.com');

const freshOutreach = generateOutreachToken('p1', 'e1');
const freshOutreachV = verifyOutreachToken(freshOutreach.token);
check('fresh outreach verifies', freshOutreachV.ok);
eq('fresh outreach projectId', freshOutreachV.ok ? freshOutreachV.data.projectId : null, 'p1');
eq('fresh outreach hash matches hashOutreachToken', freshOutreach.tokenHash, hashOutreachToken(freshOutreach.token));

const freshAvail = generateAvailabilityToken('p1', 'e1');
const freshAvailV = verifyAvailabilityToken(freshAvail.token);
check('fresh availability verifies', freshAvailV.ok);
eq('fresh availability expiry is returned', freshAvailV.ok ? freshAvailV.data.expiry : 0, freshAvail.expiry);
eq('fresh availability hash matches hashToken', freshAvail.tokenHash, hashToken(freshAvail.token));

const freshClient = generateClientAvailabilityToken('p1');
const freshClientV = verifyAvailabilityToken(freshClient.token);
check('fresh client token verifies', freshClientV.ok);
eq('fresh client token has no expertId', freshClientV.ok ? freshClientV.data.expertId : 'x', null);

const freshOnboarding = buildOnboardingOAuthState({ email: 'a:b@example.com', nonce: 'n1', timezone: 'Europe/Paris' });
const freshOnboardingV = verifyOnboardingOAuthState(freshOnboarding, 'n1');
eq('onboarding state survives a colon in the email', freshOnboardingV?.email ?? null, 'a:b@example.com');
eq('onboarding state carries the timezone', freshOnboardingV?.timezone ?? null, 'Europe/Paris');
eq('onboarding state rejects a mismatched stored nonce', verifyOnboardingOAuthState(freshOnboarding, 'n2'), null);

const freshExpertState = sign('p1:e1:n1:tok', 'expert-oauth');
const freshExpertStateV = verify(freshExpertState, 'expert-oauth');
eq('fresh expert OAuth state round-trips', freshExpertStateV.ok ? freshExpertStateV.payload : null, 'p1:e1:n1:tok');

// ─── 3. Malformed / bad-signature / expired, for every kind ──────────────────

section('malformed, tampered and expired branches');

function reasonOf(r: { ok: true } | { ok: false; reason: string }): string {
  return r.ok ? 'ok' : r.reason;
}

// One dot-separated part instead of two.
eq('opt-out: no separator → malformed',   reasonOf(verifyOptOutToken('abc')), 'malformed');
eq('outreach: no separator → malformed',  reasonOf(verifyOutreachToken('abc')), 'malformed');
eq('availability: no separator → malformed', reasonOf(verifyAvailabilityToken('abc')), 'malformed');
eq('opt-out: three parts → malformed',    reasonOf(verifyOptOutToken('a.b.c')), 'malformed');
eq('outreach: empty string → malformed',  reasonOf(verifyOutreachToken('')), 'malformed');
eq('availability: empty string → malformed', reasonOf(verifyAvailabilityToken('')), 'malformed');

// Valid signature, wrong number of payload segments.
eq('opt-out: wrong prefix → malformed',
  reasonOf(verifyOptOutToken(sign('nope:bWU=:99999999999999:ab', 'optout'))), 'malformed');
eq('opt-out: three payload segments → malformed',
  reasonOf(verifyOptOutToken(sign('optout:bWU=:99999999999999', 'optout'))), 'malformed');
eq('opt-out: email without @ → malformed',
  reasonOf(verifyOptOutToken(sign(`optout:${Buffer.from('nope', 'utf8').toString('base64url')}:99999999999999:ab`, 'optout'))), 'malformed');
eq('outreach: three payload segments → malformed',
  reasonOf(verifyOutreachToken(sign('p:e:99999999999999', 'outreach'))), 'malformed');
eq('outreach: empty projectId → malformed',
  reasonOf(verifyOutreachToken(sign(':e:99999999999999:ab', 'outreach'))), 'malformed');
eq('outreach: non-numeric expiry → malformed',
  reasonOf(verifyOutreachToken(sign('p:e:soon:ab', 'outreach'))), 'malformed');
eq('availability: five payload segments → malformed',
  reasonOf(verifyAvailabilityToken(sign('p:e:99999999999999:ab:extra', 'availability'))), 'malformed');
eq('availability: client token with empty projectId → malformed',
  reasonOf(verifyAvailabilityToken(sign('client::99999999999999:ab', 'availability'))), 'malformed');
eq('availability: expert token with empty expertId → malformed',
  reasonOf(verifyAvailabilityToken(sign('p::99999999999999:ab', 'availability'))), 'malformed');

// Tampered signatures.
function flipLastChar(token: string): string {
  const last = token.slice(-1);
  return token.slice(0, -1) + (last === 'A' ? 'B' : 'A');
}

// A wrapped state is base64url of `payload.signature`, and a base64url string's
// final character can carry bits the decoder discards — flipping it does not
// always change the decoded bytes. Tamper inside the decoded signature instead.
function tamperWrappedSignature(state: string): string {
  const decoded = Buffer.from(state, 'base64url').toString('utf8');
  const lastDot = decoded.lastIndexOf('.');
  const sig     = decoded.slice(lastDot + 1);
  const flipped = (sig[0] === '0' ? '1' : '0') + sig.slice(1);
  return Buffer.from(`${decoded.slice(0, lastDot)}.${flipped}`, 'utf8').toString('base64url');
}
eq('opt-out: tampered signature → invalid_signature',
  reasonOf(verifyOptOutToken(flipLastChar(OLD_OPTOUT_FUTURE))), 'invalid_signature');
eq('outreach: tampered signature → invalid_signature',
  reasonOf(verifyOutreachToken(flipLastChar(OLD_OUTREACH_FUTURE))), 'invalid_signature');
eq('availability: tampered signature → invalid_signature',
  reasonOf(verifyAvailabilityToken(flipLastChar(OLD_AVAIL_EXPERT))), 'invalid_signature');
eq('availability: tampered payload → invalid_signature',
  reasonOf(verifyAvailabilityToken(`${OLD_AVAIL_EXPERT.split('.')[0]}x.${OLD_AVAIL_EXPERT.split('.')[1]}`)), 'invalid_signature');
eq('opt-out: truncated signature → invalid_signature',
  reasonOf(verifyOptOutToken(`${OLD_OPTOUT_FUTURE.split('.')[0]}.${OLD_OPTOUT_FUTURE.split('.')[1].slice(0, 10)}`)), 'invalid_signature');
eq('outreach: signature from another token → invalid_signature',
  reasonOf(verifyOutreachToken(`${OLD_OUTREACH_FUTURE.split('.')[0]}.${OLD_AVAIL_EXPERT.split('.')[1]}`)), 'invalid_signature');

// Expired, freshly minted rather than fixture-based.
eq('opt-out: expired → expired',
  reasonOf(verifyOptOutToken(atClock(LONG_PAST, () => generateOptOutToken(FIXTURE_EMAIL)))), 'expired');
eq('outreach: expired → expired',
  reasonOf(verifyOutreachToken(atClock(LONG_PAST, () => generateOutreachToken('p', 'e').token))), 'expired');
eq('availability: expired → expired',
  reasonOf(verifyAvailabilityToken(atClock(LONG_PAST, () => generateAvailabilityToken('p', 'e').token))), 'expired');
eq('availability client: expired → expired',
  reasonOf(verifyAvailabilityToken(atClock(LONG_PAST, () => generateClientAvailabilityToken('p').token))), 'expired');

// OAuth states: null on every failure (no reason codes by design).
eq('onboarding state: garbage → null', verifyOnboardingOAuthState('!!!!', 'n1'), null);
eq('onboarding state: no dot → null',
  verifyOnboardingOAuthState(Buffer.from('a:b:c', 'utf8').toString('base64url'), 'b'), null);
eq('onboarding state: tampered signature → null',
  verifyOnboardingOAuthState(tamperWrappedSignature(OLD_ONBOARDING_STATE), FIXTURE_NONCE_ON), null);
eq('onboarding state: two payload parts → null',
  verifyOnboardingOAuthState(sign('a%40b.com:n1', 'onboarding-oauth'), 'n1'), null);
check('expert OAuth state: garbage → not ok', !verify('!!!!', 'expert-oauth').ok);
eq('expert OAuth state: no dot in payload → malformed',
  reasonOf(verify(Buffer.from('abc', 'utf8').toString('base64url'), 'expert-oauth')), 'malformed');
eq('expert OAuth state: tampered signature → invalid_signature',
  reasonOf(verify(tamperWrappedSignature(OLD_EXPERT_OAUTH_STATE), 'expert-oauth')), 'invalid_signature');
check('the old inline verifier also rejects the tampered state',
  !oldVerifyExpertState(tamperWrappedSignature(OLD_EXPERT_OAUTH_STATE), FIXTURE_NONCE_EX).ok);

// ─── 4. The shared primitives themselves ─────────────────────────────────────

section('lib/hmacToken primitives');

check('constantTimeEqual: equal strings',        constantTimeEqual('abc', 'abc'));
check('constantTimeEqual: differing same length', !constantTimeEqual('abc', 'abd'));
check('constantTimeEqual: shorter actual',        !constantTimeEqual('abc', 'ab'));
check('constantTimeEqual: longer actual',         !constantTimeEqual('abc', 'abcd'));
check('constantTimeEqual: empty vs non-empty',    !constantTimeEqual('', 'a'));
check('constantTimeEqual: both empty',            constantTimeEqual('', ''));

eq('sign is deterministic for the same payload',
  sign('p:e:1:n', 'availability'), sign('p:e:1:n', 'availability'));
check('a purpose does not accept another purpose\'s wire format',
  !verify(sign('p:e:1:n', 'availability'), 'expert-oauth').ok);
eq('detached verify returns the raw payload',
  verify(sign('p:e:1:n', 'outreach'), 'outreach').ok
    ? (verify(sign('p:e:1:n', 'outreach'), 'outreach') as { payload: string }).payload
    : null,
  'p:e:1:n');

const shortSecret = process.env.AVAILABILITY_TOKEN_SECRET;
process.env.AVAILABILITY_TOKEN_SECRET = 'too-short';
let threw = false;
try { sign('p:e:1:n', 'availability'); } catch { threw = true; }
check('sign throws when the secret is under 32 characters', threw);
eq('verify degrades to invalid_signature without a usable secret',
  reasonOf(verify(OLD_AVAIL_EXPERT, 'availability')), 'invalid_signature');
process.env.AVAILABILITY_TOKEN_SECRET = shortSecret;

summary();
